service: teamtime

provider:
  name: aws
  region: us-east-1
  runtime: provided
  httpApi:
    payload: '1.0'
  vpc:
    securityGroupIds:
      - sg-f311ccbb
    subnetIds:
      - subnet-f48b4d93
      - subnet-9d6aedd7
      - subnet-742bd65a
      - subnet-5d897a01
      - subnet-fe0d1bc1
      - subnet-e5fa74ea
  environment:
    APP_ENV: production
    DB_CONNECTION: mysql
    DB_HOST: teamtime-new.cnwzmaqm9ufv.us-east-1.rds.amazonaws.com
    DB_PORT: 3306
    DB_DATABASE: teamtime_db
    DB_USERNAME: teamtime_new
    DB_PASSWORD: followspabbyontwitch
    MIX_ASSET_URL: https://teamtime-s3.s3.amazonaws.com

plugins:
  - ./vendor/bref/bref

package:
  exclude:
    - node_modules/**
    - public/storage
    - resources/assets/**
    - storage/**
    - tests/**

functions:
  website:
    handler: public/index.php
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      -   httpApi: '*'
  artisan:
    handler: artisan
    timeout: 120 # in seconds
    layers:
      - ${bref:layer.php-74} # PHP
      - ${bref:layer.console} # The "console" layer
